Feature/380 projektanmerkungen om pm
Gepardec/mega pull request #404
Opened 2021-07-19 15:29 UTC by Ollitod

2021-07-20 05:29 UTC, patholzer commented on mega-zep-backend/src/main/java/com/gepardec/mega/db/entity/project/ProjectComment.java
> +        updatedDate = LocalDateTime.now(); // TODO
Remove updatedDate not null constraint and the temporary workaround

2021-07-20 05:38 UTC, patholzer requested changes
updatedDate not null constraint entfernen und das temporäre setzen im @PrePersist entfernen - sonst schauts super aus!

2021-07-20 05:50 UTC, Ruhsi commented on mega-zep-backend/src/main/java/com/gepardec/mega/rest/ProjectCommentResource.java
> +    public ProjectCommentDto getProjectComment(
We are in the ProjectCommentRessource, therefore only get, create and update instead of getProjectComment, etc. -> same in service

2021-07-20 05:50 UTC, Ruhsi commented on mega-zep-backend/src/main/java/com/gepardec/mega/service/api/project/ProjectCommentService.java
> +    List<ProjectCommentDto> findProjectCommentsForProjectNameInRange(String projectName, LocalDate from, LocalDate to);
findForProjectNameInRange

2021-07-20 05:50 UTC, Ruhsi commented on mega-zep-frontend/src/main/angular/frontend/src/app/modules/shared/services/project-comment/project-comment.service.ts
> +  getProjectComment(monthYear: string, projectName: string) {
naming

2021-07-21 07:12 UTC, patholzer submitted a review, later dismissed

2021-07-22 06:20 UTC, patholzer approved these changes

2021-07-22 07:48 UTC, merged