#484 replace employee emails from test files
Gepardec/mega pull request #485
Opened 2021-11-03 11:52 UTC by andreas-repo

removed all employee email addresses from test files, ran all test classes where changes tookplace locally to test if everything is still working as intented

2021-11-03 12:04 UTC, phiwu-gpdec requested changes

2021-11-03 12:04 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/rest/TestResource.java
>                  "Thomas",
Hier steht noch Thomas drinne, bitte auch alle anderen Werte überprüfen, ob noch Namen drinnen stehen. Wenn Namen und Mitarbeiternummern notwending sind (z.B. für ZEP) dann bitte drinnen lassen.

2021-11-03 12:31 UTC, andreas-repo commented on mega-zep-backend/src/main/java/com/gepardec/mega/rest/TestResource.java
>                  "Thomas",
sollte jetzt alles anonymisiert sein.

2021-11-04 08:11 UTC, Ruhsi approved these changes

2021-11-04 08:16 UTC, andreas-repo commented on mega-zep-backend/src/main/java/com/gepardec/mega/rest/TestResource.java
>                  "Thomas",
Es sollten jetzt alle verweise auf Mitarbeiter und persönliche Daten entfernt sein.

2021-11-04 08:29 UTC, phiwu-gpdec approved these changes

2021-11-04 08:52 UTC, merged