#478 calculates amount of billable and non billable hours per project
Gepardec/mega pull request #488
Opened 2021-11-17 09:31 UTC by andreas-repo

added aggregation function to ManagementResource.class
added  aggregatedBillableWorkTimeInSeconds and aggregatedNonBillableWorkTimeInSeconds to ProjectManagementEntry.class

2021-11-17 12:12 UTC, phiwu-gpdec requested changes

2021-11-17 12:12 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/rest/ManagementResource.java
>          for (ProjectEmployees currentProject : projectEmployees) {
Hier wären Streams möglich.

2021-11-17 12:12 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/rest/ManagementResource.java
> +                    long hours = Long.parseLong(billableTime.split(":")[0]);
Ist `split()` jedes Mal erfolgreich? Ein Überprüfung ob überhaupt ein Element bzw. ob ein Element an Position 0 und 1 vorhanden sind, wäre nicht schlecht.

2021-11-17 12:12 UTC, phiwu-gpdec commented on mega-zep-backend/src/test/java/com/gepardec/mega/rest/ManagementResourceTest.java
> +        Assert.assertTrue(entrymmustermann.isPresent());
Static call und darunter mit static import - nicht mischen. Hat zwar programmtechnisch keine Auswirkungen aber schaut nicht schön aus.

2021-11-17 13:06 UTC, Ruhsi requested changes

2021-11-17 13:06 UTC, Ruhsi commented on mega-zep-backend/src/main/java/com/gepardec/mega/rest/ManagementResource.java
>          for (ProjectEmployees currentProject : projectEmployees) {
Die 2 Variablen bitte löschen. Werden nicht mehr verwendet.

2021-11-17 13:06 UTC, Ruhsi commented on mega-zep-backend/src/main/java/com/gepardec/mega/rest/ManagementResource.java
> +                    long hours = Long.parseLong(billableTime.split(":")[0]);
Es kommt zwar von ZEP immer das Format "HH:mm", auch wenn nichts eingetragen ist ("00:00"). Ein Null-Check wäre aber hier trotzdem sicherer

2021-11-17 13:06 UTC, Ruhsi commented on mega-zep-backend/src/test/java/com/gepardec/mega/rest/ManagementResourceTest.java
>          // TODO add concrete parameter values instead of any
TODO entfernen. ArgumentMatchers.anyString() passt so 👍

2021-11-17 13:06 UTC, Ruhsi commented on mega-zep-backend/src/test/java/com/gepardec/mega/rest/ManagementResourceTest.java
> +        // TODO add concrete parameter values instead of any
TODO entfernen

2021-11-17 13:06 UTC, Ruhsi commented on mega-zep-backend/src/test/java/com/gepardec/mega/rest/ManagementResourceTest.java
> +        Assert.assertTrue(projectRgkkcc.isPresent());
assertTrue(...) ohne Assert.

2021-11-17 13:06 UTC, Ruhsi commented on mega-zep-backend/src/test/java/com/gepardec/mega/rest/ManagementResourceTest.java
> +        //assert billable/non billable time
Leerzeichen nach //

2021-11-17 13:06 UTC, Ruhsi commented on mega-zep-backend/src/test/java/com/gepardec/mega/rest/ManagementResourceTest.java
> +        // TODO add concrete parameter values instead of any
TODO entfernen

2021-11-18 06:42 UTC, Ruhsi requested changes

2021-11-18 06:42 UTC, Ruhsi commented on mega-zep-backend/src/main/java/com/gepardec/mega/rest/ManagementResource.java
> +        if (entries != null && entries.get(0) != null) {
Das entries.get(0) != null ist hier nicht nötig. Wenn entries leer ist, wirft .map keine Exception und der Initial Value von reduce greift.

2021-11-18 06:42 UTC, Ruhsi commented on mega-zep-backend/src/main/java/com/gepardec/mega/rest/ManagementResource.java
> +                                long hours = Long.parseLong(billableTime.split(":")[0]);
Hier bitte noch den null-Check und blank-Check von billable time einbauen und bitte auf projectTime (oä.) umbenennen, hier kommen billable times und nonbillable times rein.

2021-11-18 10:03 UTC, merged