#471 Zeitenüberschneidungen erkennen
Gepardec/mega pull request #491
Opened 2021-11-22 11:52 UTC by andreas-repo

-- added TimeOverlapCalculator.java
-- added calculate method
-- added isOverlapping() method
-- added TimeOverlapCalculatorTest

2021-11-22 13:05 UTC, Ruhsi requested changes

2021-11-22 13:05 UTC, Ruhsi commented on mega-zep-backend/src/test/java/com/gepardec/mega/domain/calculation/time/TimeOverlapCalculatorTest.java
> +public class TimeOverlapCalculatorTest {
nicht public

2021-11-22 13:05 UTC, Ruhsi commented on mega-zep-backend/src/main/java/com/gepardec/mega/domain/calculation/time/TimeOverlapCalculator.java
> +                    tempWarning.add("Überschneidungen bitte Kontrollieren, bezüglich Ausnahmen bei Reisen bitte Rücksprache mit HR");
besser einen enum bauen. zb TimeOverlap.CONTROL_WARNINGS und den Text selbst dann im Frontend einbauen. Dann würden auch weiterhin Übersetzungen funktionieren.

2021-11-22 13:05 UTC, Ruhsi commented on mega-zep-backend/src/main/java/com/gepardec/mega/domain/calculation/time/TimeOverlapCalculator.java
> +                    TimeWarning tempTimeWarning = new TimeWarning();
Hier wäre ein Lombok.Builder schöner oder zumindest ein Konstruktor für date und warnings

2021-11-22 13:13 UTC, andreas-repo commented on mega-zep-backend/src/test/java/com/gepardec/mega/domain/calculation/time/TimeOverlapCalculatorTest.java
> +
In den anderen Tests an denen ich mich orientiert habe wie zB CoreWorkingHoursCalculatorTest, ExceededMaximumWorkingHoursPerDayCalculatorTest, etc gibt es auch keine @QuarkusTest Annotation, soll ich sie dort auch gleich mit einbauen?

2021-11-22 13:30 UTC, Ruhsi commented on mega-zep-backend/src/test/java/com/gepardec/mega/domain/calculation/time/TimeOverlapCalculatorTest.java
> +
Nein sorry, mein Fehler. Wenn kein CDI benötigt wird, braucht man auch kein @QuarkusTest.

2021-11-23 06:18 UTC, Ruhsi submitted a review, later dismissed

2021-11-23 12:11 UTC, phiwu-gpdec requested changes

2021-11-23 12:11 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/domain/calculation/time/TimeOverlapCalculator.java
> +        for (int i = 0; i < projectEntries.size(); i++) {
Warum hier keine Streams oder zumindest `foreach()`?

2021-11-23 12:11 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/domain/calculation/time/TimeOverlapCalculator.java
> +            for (int j = i + 1; j < projectEntries.size(); j ++) {
Streams oder `foreach()`.

2021-11-23 12:11 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/domain/calculation/time/TimeOverlapCalculator.java
> +                    List<String> tempWarning = new ArrayList<>();
Was ist mit dieser Variable?

2021-11-23 12:11 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/domain/calculation/time/TimeOverlapCalculator.java
> +    private boolean isOverlapping(ProjectEntry elementOne, ProjectEntry elementTwo) {
elementOne, elementTwo?

2021-11-23 12:11 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/domain/calculation/time/TimeOverlapCalculator.java
> +        if (elementOne.getToTime().equals(elementTwo.getFromTime()) || elementOne.getFromTime().equals(elementTwo.getToTime())) {
Null-Check bei `getToTime()` und `getFromTime()`?

2021-11-23 12:11 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/domain/model/monthlyreport/TimeOverlapWarningType.java
> +    TIME_OVERLAP;
Enum mit Parametern statt fixem String "time".

2021-11-23 12:11 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/service/impl/monthlyreport/WarningCalculator.java
> +        for (WarningCalculationStrategy<TimeOverlapWarning> calculator : timeOverlapCalculators) {
`foreach()`

2021-11-24 08:39 UTC, andreas-repo commented on mega-zep-backend/src/main/java/com/gepardec/mega/domain/model/monthlyreport/TimeOverlapWarningType.java
> +    TIME_OVERLAP;
@phiwu-gpdec Alle WarningTypes (Journey, etc) sind auf die gleiche Art aufgebaut. Soll ich bei allen Änderungen vornehmen?

2021-11-24 10:30 UTC, andreas-repo commented on mega-zep-backend/src/main/java/com/gepardec/mega/service/impl/monthlyreport/WarningCalculator.java
> +        for (WarningCalculationStrategy<TimeOverlapWarning> calculator : timeOverlapCalculators) {
@phiwu-gpdec Ist doch eh schon ein foreach? Oder meinst du als Stream?

2021-11-24 10:50 UTC, andreas-repo commented on mega-zep-backend/src/main/java/com/gepardec/mega/domain/calculation/time/TimeOverlapCalculator.java
> +                    List<String> tempWarning = new ArrayList<>();
Hopala die ist mir entgangen beim refactoring.

2021-11-26 07:21 UTC, phiwu-gpdec requested changes

2021-11-26 07:21 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/domain/model/monthlyreport/TimeOverlapWarning.java
> +
Leerzeile

2021-11-26 07:21 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/domain/model/monthlyreport/TimeOverlapWarningType.java
> +    TIME_OVERLAP;
Wenn alle so sind, dann lass es.

2021-11-26 07:21 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/service/impl/monthlyreport/WarningCalculator.java
> +
Leerzeile

2021-11-26 07:58 UTC, phiwu-gpdec requested changes

2021-11-26 07:58 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/domain/model/monthlyreport/TimeOverlapWarning.java
> +
Leerzeile

2021-11-26 07:58 UTC, phiwu-gpdec commented on mega-zep-backend/src/main/java/com/gepardec/mega/domain/model/monthlyreport/TimeOverlapWarning.java
> +
Leerzeile

2021-11-26 08:16 UTC, phiwu-gpdec approved these changes

2021-11-26 08:35 UTC, merged